Benjamin Wilson
Lab 6
October 13, 2021

Script started on 2021-10-13 15:25:51-06:00 [TERM="xterm-256color" TTY="/dev/pts/0" COLUMNS="192" LINES="11"]
]0;ben@Clover-VirtualBox: ~/cse113/lab6[01;32mben@Clover-VirtualBox[00m:[01;34m~/cse113/lab6[00m$ make difference
gcc -g -Wall difference.c -o difference
]0;ben@Clover-VirtualBox: ~/cse113/lab6[01;32mben@Clover-VirtualBox[00m:[01;34m~/cse113/lab6[00m$ ./difference

The difference between the sum of the squares and square of the sum is: 25164150

]0;ben@Clover-VirtualBox: ~/cse113/lab6[01;32mben@Clover-VirtualBox[00m:[01;34m~/cse113/lab6[00m$ exit
exit

Script done on 2021-10-13 15:26:07-06:00 [COMMAND_EXIT_CODE="0"]
