Benjamin Wilson
Lab 6
October 13, 2021

Script started on 2021-10-13 15:24:59-06:00 [TERM="xterm-256color" TTY="/dev/pts/0" COLUMNS="192" LINES="11"]
]0;ben@Clover-VirtualBox: ~/cse113/lab6[01;32mben@Clover-VirtualBox[00m:[01;34m~/cse113/lab6[00m$ make smallest
gcc -g -Wall smallest.c -o smallest
]0;ben@Clover-VirtualBox: ~/cse113/lab6[01;32mben@Clover-VirtualBox[00m:[01;34m~/cse113/lab6[00m$ ./smallest

 The smallest number divisible by 1-20 is 232792560

]0;ben@Clover-VirtualBox: ~/cse113/lab6[01;32mben@Clover-VirtualBox[00m:[01;34m~/cse113/lab6[00m$ exit
exit

Script done on 2021-10-13 15:25:39-06:00 [COMMAND_EXIT_CODE="0"]
